matrix:
  include:
    - language: node_js
      install:
        - npm --prefix ./api install
      script:
        - npm --prefix ./api run lint
        - npm --prefix ./api run build
    - language: node_js
      install:
        - npm --prefix ./app install
      script:
        - npm --prefix ./app run lint
        - npm --prefix ./app run build
